### ISSUE TITLE
登录后台经常会有bug弹出

### ISSUE THREAD

**Issue by cnluminous** [Tai7sy/card-system#201]
msg:Cannot read property 'hasOwnProperty' of undefinedurl: https://shop.cnluminous.com/admin/dashboard/index
--
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at a.ChartData (https://shop.cnluminous.com/dist/js/chunk-45efcb95.3223a147.js:1:112020)
    at ir.get (https://shop.cnluminous.com/dist/js/chunk-vendors.e107624d.js:41:30801)
    at ir.evaluate (https://shop.cnluminous.com/dist/js/chunk-vendors.e107624d.js:41:31802)
    at a.ChartData (https://shop.cnluminous.com/dist/js/chunk-vendors.e107624d.js:41:33495)
    at a.initChart (https://shop.cnluminous.com/dist/js/chunk-45efcb95.3223a147.js:1:113103)
    at a.updateChart (https://shop.cnluminous.com/dist/js/chunk-45efcb95.3223a147.js:1:114248)
    at a.updateChart (https://shop.cnluminous.com/dist/js/chunk-45efcb95.3223a147.js:1:114704)
    at a.<anonymous> (https://shop.cnluminous.com/dist/js/chunk-45efcb95.3223a147.js:1:121920)
    at Array.<anonymous> (https://shop.cnluminous.com/dist/js/chunk-vendors.e107624d.js:41:12877)
    at fe (https://shop.cnluminous.com/dist/js/chunk-vendors.e107624d.js:41:12272)
--
请问这是什么情况。

**Comment by Tai7sy** [comment]
统计数据不足导致图表没渲染吧, 有发现功能异常吗

**Comment by cnluminous** [comment]
经常无法打开添加商品和卡密页，需要刷新一次

**Comment by Tai7sy** [comment]
后台有错误日志吗

**Comment by cnluminous** [comment]
无错误日志
