### ISSUE TITLE
网站无法读取列表

### ISSUE THREAD

**Issue by HurryBy** [Tai7sy/card-system#467]
有时候行有时候就不行了
没套cdn

msg:Cannot read properties of undefined (reading 'data')
url: 1/admin/product/list
TypeError: Cannot read properties of undefined (reading 'data')
    at a.<anonymous> (1/dist/js/app.1b6120f2.js:1:157362)
    at a.t._render (1/dist/js/chunk-vendors.bd699b62.js:41:23849)
    at a.r (1/dist/js/chunk-vendors.bd699b62.js:41:27940)
    at ir.get (1/dist/js/chunk-vendors.bd699b62.js:41:30800)
    at ir.run (1/dist/js/chunk-vendors.bd699b62.js:41:31533)
    at Jn (1/dist/js/chunk-vendors.bd699b62.js:41:29740)
    at Array.<anonymous> (1/dist/js/chunk-vendors.bd699b62.js:41:12877)
    at fe (1/dist/js/chunk-vendors.bd699b62.js:41:12272)

**Comment by HurryBy** [comment]
还弄着弄着就无法访问了[https://s3.bmp.ovh/imgs/2021/11/d2543b7971ad27b5.png](https://s3.bmp.ovh/imgs/2021/11/d2543b7971ad27b5.png)
