### ISSUE TITLE
apache2.4.52版本可以支持ipv6地址

### ISSUE THREAD

**Issue by SmilingCoffins** [Tai7sy/card-system#507]
搭建风铃没反应

**Comment by SmilingCoffins** [comment]
我构建数据库失败
问题很多离线下载3.15版本没有vendor提示报错了
构建好了数据库 该设置都设置了提示Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@example.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache Server at [gtav.ml](http://xx.xl/) Port 80
还用另一台Linux安装出现另一直情况构建数据库
PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 2

Deprecated: Method ReflectionParameter::getClass() is deprecated in /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 2
PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 2

Deprecated: Method ReflectionParameter::getClass() is deprecated in /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 2
PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 2

Deprecated: Method ReflectionParameter::getClass() is deprecated in /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 2
PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 2

Deprecated: Method ReflectionParameter::getClass() is deprecated in /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 2
PHP Fatal error:  Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) in /www/wwwroot/192.168.8.6/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 2
PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php:2
Stack trace:
#0 /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php(2): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php(2): Illuminate\Container\Container->resolveDependencies()
#2 /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php(2): Illuminate\Container\Container->build()
#3 /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php(2): Illuminate\Container\Container->resolve()
#4 /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(2): Illuminate\Container\Container->make()
#5 /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php(2): Illuminate\Foundation\Application->make()
#6 /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php(2): Illuminate\Container\Container->Illuminate\Container\{closure}()
#7 /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php(2): Illuminate\Container\Container->build()
#8 /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php(2): Illuminate\Container\Container->resolve()
#9 /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(2): Illuminate\Container\Container->make()
#10 /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(2): Illuminate\Foundation\Application->make()
#11 /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(2): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#12 /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(2): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole()
#13 /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(2): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#14 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#15 {main}
  thrown in /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 2

**Comment by SmilingCoffins** [comment]
卸载重新安装php 8.0后提示变短了 
Deprecated: Method ReflectionParameter::getClass() is deprecated in /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 2

Deprecated: Method ReflectionParameter::getClass() is deprecated in /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 2

Deprecated: Method ReflectionParameter::getClass() is deprecated in /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 2

Deprecated: Method ReflectionParameter::getClass() is deprecated in /www/wwwroot/192.168.8.6/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 2

**Comment by SmilingCoffins** [comment]
还有提个建议手机端操作后台不好用 把隐藏状态栏加在概括那块这样比较人性
![T7HJ0D%2%1WRAAJ12111QL](https://user-images.githubusercontent.com/86954168/155071877-003df647-4dfe-4821-827c-9584ce6cf1ff.png)
化

**Comment by SmilingCoffins** [comment]
apache 伪静态不添加location / {
    try_files $uri $uri/ /index.php?$query_string;
}
能打开主页 域名/admin提示报错
Not Found
The requested URL was not found on this server.

Apache Server at gtav.ml Port 80
点击商品报错提示
错误
Request failed with status code 404

**Comment by SmilingCoffins** [comment]
> ipv6和一个PHP程序又能有什么关系呢



> ipv6和一个PHP程序又能有什么关系呢

[](https://user-images.githubusercontent.com/86954168/155071877-003df647-4dfe-4821-827c-9584ce6cf1ff.png)还有提个建议手机端操作后台不好用 把隐藏状态栏加在概括那块这样比较人性
T7HJ0D%2%1WRAAJ12111QL
化如果能设计成油管那个隐藏就很好

**Comment by SmilingCoffins** [comment]
> ipv6和一个PHP程序又能有什么关系呢

php7.4
apache2.4
伪静态不添加location / {
try_files $uri $uri/ /index.php?$query_string;
}
能打开主页 域名/admin提示报错
Not Found
The requested URL was not found on this server.

Apache Server at gtav.ml Port 80
点击商品报错提示
错误
Request failed with status code 404

**Comment by Tai7sy** [comment]
@SmilingCoffins 自己不看安装教程瞎捣鼓

**Comment by SmilingCoffins** [comment]
> 

就是按照安装教程安装没瞎鼓捣，每一步都没有错误操作

**Comment by SmilingCoffins** [comment]
> @SmilingCoffins 自己不看安装教程瞎捣鼓

多安装重新安装几次
不添加伪静态
![image](https://user-images.githubusercontent.com/86954168/155301425-db63911e-e451-419b-8b02-03e21f8ff96d.png)
添加伪静态直接打不开网页了
